---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# suffolk-wam-report

<!-- badges: start -->
<!-- badges: end -->

The goal of suffolk-wam-report is to provide a reproducible way to generate the Suffolk Waste Annual Monitoring Report automatically each year. This report is required to be submitted to central government every December(?).

All plots and tables have been styled to be consistent with the Suffolk County Council's brand.

Do note that while this is a nice template for the standard sections of the report. Year-on-year changes will demand some more in-depth investigation. For example, in 20/21 a deeper dive into sewage sludge.

# Data Sources
The following data sources are needed for this report:
  - Waste Data Interrogator [2019](https://www.data.gov.uk/dataset/d409b2ba-796c-4436-82c7-eb1831a9ef25/2019-waste-data-interrogator) and [2020](https://www.data.gov.uk/dataset/bb40d091-a346-4b75-aa54-df7d347bed93/2020-waste-data-interrogator). A new version is published around September/October every year.
  - [Remaining Landfill Capacity](https://www.data.gov.uk/dataset/237825cb-dc10-4c53-8446-1bcd35614c12/remaining-landfill-capacity).
  - [Local authority collected waste](https://www.gov.uk/government/statistical-data-sets/env18-local-authority-collected-waste-annual-results-tables). Usually updated in January.

Currently the last version used for the 21/22 report:
  - WDI, published May 2022.
  - RLC, published February 2022.
  - LACW, published January 2022.

Note that all these sources may have updates or amendments throughout the year, meaning totals can change within and between years.
